name: Dockerize SCM

on:
  push
env:
  IMAGE_NAME: actionshackathon
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Docker Image for Development Environment
        run: docker build . --file Dockerfile
