name: Dockerize SCM

on:
  push
env:
  IMAGE_NAME: actionshackathon
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build and run
        run: docker build . --file Dockerfile -t foo . && docker run -it foo
        
     
      
